### ISSUE TITLE
fuse: mountpoint is not empty

### ISSUE THREAD

**Issue by xcxc12344** [angeluslove/qt-for-raspberry#1]
你好，我制作镜像时，先把U盘格式成exFAT格式后，出现了这个问题，请问如何解决
FUSE exfat 1.2.5
WARN: volume was not unmounted cleanly.
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
mount fail, exit now

**Comment by angeluslove** [comment]
首先确定一下你的系统版本是多少，新的版本据说不支持备份。
还有运行脚本的时候最好先切换到root权限下
默认挂载的是 /dev/sda1 
你需要确认下你的u盘是不是sda1
